import type { Metadata } from 'next';
import { Inter, Noto_Sans } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { Provider } from 'react-redux';
import { wrapper } from '@/store';

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  ...rest
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { store, props } = wrapper.useWrappedStore(rest);

  return (
    <Provider store={store}>
      <html lang="en">
        <body className={notoSans.className}>
          <Header />
          {children}
          <div id="root-modal" />
        </body>
      </html>
    </Provider>
  );
}
